version: "3.8"

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"      # HTTP port for proxy
      - "443:443"    # HTTPS port for proxy
      - "8080:8080"  # Admin API port
    volumes:
      - ssl-certs:/root/.local/share/certmagic  # For SSL certificate storage
    env_file:
      - .env
    depends_on:
      - db
    cap_add:
      - NET_BIND_SERVICE  # Required to bind to ports 80 and 443
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - viacortex-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=viacortex
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viacortex-network
    restart: unless-stopped
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  ssl-certs:
    driver: local
  postgres_data:
    driver: local

networks:
  viacortex-network:
    driver: bridge