root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/viacortex"
bin = "./tmp/app"
full_bin = "./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "postgres_data"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"